### ISSUE TITLE
Add GetExports Documentation

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-doc#124]

**Comment by t92549** [comment]
@GCHQDeveloper314 would you consider this done now with your [export operations](https://github.com/gchq/gaffer-doc/blob/cdfeb99614f5c8451e700ce2b08696e05f18a830/docs/reference/operations-guide/export.md) reference page?

**Comment by GCHQDeveloper314** [comment]
From the title, this means to add documentation for `operation.impl.export.GetExports`. This is not documented at all. If it were documented then it would go on that page.
