### ISSUE TITLE
Improve NamedOperation documentation

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-doc#156]
1. Doc for NamedOperation in fact includes doc for AddNamedOperation, DeleteNamedOperation which are not otherwise documented.
2. The doc does not include the readAccessRoles/writeAccessRoles.
3. The doc does not list all of the required fields.
4. The doc requires an improved example of passing parameters of different types, e.g. Long into a NamedOperation. The Java example inserts a Long in a Map and passes that. The JSON equivalent does not do this wrapping. This apparently is correct but unintuitive for a user.

**Comment by t92549** [comment]
I would consider this closed by https://github.com/gchq/gaffer-doc/pull/322

**Comment by GCHQDeveloper314** [comment]
> I would consider this closed by #322

At a glance, t[he current doc does contain the information requested above](https://gchq.github.io/gaffer-doc/latest/reference/operations-guide/named/). Though it wasn't added as part of that PR. It was already in the old docs.

**Comment by t92549** [comment]
Agreed, though the new docs make the structure a lot clearer
