### ISSUE TITLE
Add Documentation for new Koryphe Functions

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-doc#195]
Add Example docs for:
* DefaultIfEmpty
* DefaultIfNull
* FirstValid
* IterableFlatten
* IterableLongest
* Longest
* MultiplyLongBy
* ReverseString
* StringPrepend
* StringAppend
* StringJoin
* StringRegexSplit
* StringRegexReplace
* StringReplace
* StringSplit
* StringTrim
* StringTruncate

**Comment by t92549** [comment]
This has already been merged by d2e7d7a5f29b77b801e7e02bc865888f91270f42
