### ISSUE TITLE
Replace MockAccumuloStore usage

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#209]
Similar to https://github.com/gchq/gaffer-tools/issues/865, MockAccumuloStore should be replaced in the docs and code examples.

**Comment by n3101** [comment]
@t92549 Good point!

**Comment by gk926** [comment]
Hi, I don't mind picking this one up. Will be my first contribution though so please bear with me....

**Comment by t92549** [comment]
Moved to v1.20.0 as it relies on https://github.com/gchq/Gaffer/pull/2508 which will be in Gaffer v1.19.0
