### ISSUE TITLE
Document the separate read & write access controls for graphs

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-doc#219]
https://github.com/gchq/Gaffer/issues/2295 changed the way graph access controls are set. This is not documented. This may also apply to other types of object.

**Comment by m29827** [comment]
Changes on this branch are ready for a PR but are dependent on the updates to AddNamedOperation contained in https://github.com/gchq/Gaffer/issues/2476 being merged and a new Gaffer version containing them being made available.

**Comment by n3101** [comment]
@m29827 I haven't seen this doc in properly assembled form but skimmed your commits. I spotted a couple of typos: 

"However public access can be disallow    by setting the property"
                                                                  ^^
"The full example we saw in the the User Guide"
                                                     ^^^

Secondly, I'm not sure I understand this concept:

"Note that "graphAuths" is mutually exclusive with the "readAccessPredicate" and "writeAccessPredicate" settings"

What happens if you put entries in all three? Does graphAuths take precedence; or the predicates take precedence; or what?

**Comment by m29827** [comment]
@n3101 I've corrected those typos. Regarding the "mutually exclusive" documentation - the AccessControlledResouce property readAccessPredicate and can't be used in combination with the historic graphAuths, an Exception will be thrown if an attempt is made to configure both. The predicates give additional fine grained controls over and above the old-style checks against a list of auths.

**Comment by n3101** [comment]
@m29827 Thanks. 
"The predicates give additional fine grained controls over and above the old-style checks against a list of auths."   
Should the team be discussing whether to deprecate the "old-style" checks and remove them in v2.0?

**Comment by n3101** [comment]
@m29827 https://github.com/gchq/Gaffer/issues/2476 has now been merged. Can you submit your PR for this issue now?

**Comment by m29827** [comment]
Hi @n3101 - not at the moment, it requires a version of Gaffer to be built & published containing those changes so the dependency can be updated.

**Comment by n3101** [comment]
@m29827 Ok thanks.

**Comment by n3101** [comment]
@m29827 OK,  gchq/Gaffer#2476 has now been released in gaffer v1.19. If you can submit your PR for this issue now we will try to get it out in the October release. Cheers.

**Comment by m29827** [comment]
Hi @n3101, I've updated the dependencies and opened a PR.

**Comment by t92549** [comment]
Resolved by #232
