### ISSUE TITLE
Change gh-pages to place docs into subfolder

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-doc#255]
The v1 docs (currently in the master branch) are put straight into the root of the gh-pages branch once built.
This is going to be changed with the v2 docs and separate versioned folders are to be used in gh-pages instead.
To prepare for this the existing docs in gh-pages need to be moved into a subdirectory and a redirect configured to send browsers to this new folder.

**Comment by t92549** [comment]
Fixed by #259
