### ISSUE TITLE
Links derived from main Gaffer repo are broken

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-doc#264]
The scripts for building the Gaffer 1 docs pull markdown from READMEs in the [gchq/Gaffer](https://github.com/gchq/Gaffer) `master` branch. These files contain links back to the `gh-pages` docs website.

As part of the transition to the new versioned documentation, the Gaffer 1 docs were moved to a `/v1docs/` subfolder in `gh-pages`. The old location was referenced by various links in [gchq/Gaffer](https://github.com/gchq/Gaffer). These were fixed but that fix has not yet made it into the `master` branch.

As a result internal links in the Gaffer docs which are derived from the [gchq/Gaffer](https://github.com/gchq/Gaffer) master branch are broken. Once the next Gaffer 1 release is performed, the problem will be resolved - as the links in `master` will be updated.

Rather than waiting for the next Gaffer 1 release, the HTML in `gh-pages` could be updated manually to fix the broken links now.

**Comment by t92549** [comment]
Fixed by #265. Long term this won't happen after the next Gaffer 1 release
