### ISSUE TITLE
Update Gaffer 2.0 doc for HBase & Parquet 

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-doc#270]
The list of available stores https://gchq.github.io/gaffer-doc/v1docs/summaries/stores.html is linked from the gaffer 2.0 readme page and includes HBase & Parquet. These need a "Gaffer 1.* only" flag or something.

**Comment by t92549** [comment]
The link you provided is for the v1docs, the v2docs won't list these stores. The Gaffer 2 README will be updated to not point to the v1docs in this [ticket](https://github.com/gchq/Gaffer/issues/2600), so this issue can be closed as nothing has to be done in gaffer-doc
