### ISSUE TITLE
Document all StoreProperties better

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#271]
In the v1 docs there is no real documentation on StoreProperties. This can lead to confusions where a StoreProperty isn't known about, like in https://github.com/gchq/Gaffer/issues/2596 where the `STRICT_JSON_DEFAULT` was originally not known about, then the default was questioned so people get the feature without needing to set the property. If this property was just better documented then this would never have happened.
The documentation on StoreProperties should describe each property, if they are store specific, and what the defaults are if they exist.

**Comment by GCHQDeveloper314** [comment]
This can be realised as a new section [on the store page of the administration guide](https://github.com/gchq/gaffer-doc/blob/v2docs/docs/administration-guide/gaffer-stores/store-guide.md).
