### ISSUE TITLE
schema structure documentation needs review

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-doc#275]
The "getting started" documentation recommends:

"The Schema file can be broken down into small parts, we encourage at least 2 files:

[elements.json](https://github.com/gchq/gaffer-doc/blob/master/user/src/main/resources/RoadUse/schema/elements.json)
[types.json](https://github.com/gchq/gaffer-doc/blob/master/user/src/main/resources/RoadUse/schema/types.json)
Splitting the schema up into these 2 files helps to illustrate the different roles that the schemas fulfil.
"

We don't do this. Is this advice out of date? Perhaps it should say that the schema can be split across multiple files? What naming conventions apply? Can they be overridden? etc

**Comment by GCHQDeveloper314** [comment]
I'll investigate this and add the findings to the Schema documentation page. This page doesn't exist in the new docs yet so it can be migrated as part of this issue.

**Comment by GCHQDeveloper314** [comment]
Some answers to the questions posed above:

1. We don't do this. Is this advice out of date?
The advice makes sense for a simple graph when getting started. It's not out of date.
2. Perhaps it should say that the schema can be split across multiple files?
The [old developer schema docs](https://gchq.github.io/gaffer-doc/v1docs/getting-started/developer-guide/schemas.html) do touch on this, but more detail would be useful. They can be split across as many files as you want.
3. What naming conventions apply?
None, other than the files need to be JSON (`.json`) and need to be in the appropriate directory when using a REST.
4. Can they be overridden?
There's no real convention to override. When using Java directly you can use any filename you want or no file at all, so long as you pass in valid JSON.

To resolve this issue, the new docs should have an improved version of the page linked which contains everything said here.
