### ISSUE TITLE
Improve usability of v1 docs

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-doc#284]
Currently there's no way to easily get back to the top of the page after scrolling some way down. [There's a plugin which can do this](https://github.com/dogatana/honkit-plugin-back-to-top-button). We should also add a way to navigate to the v2 docs pages from the v1 pages, if possible.

**Comment by GCHQDeveloper314** [comment]
Adding a way to navigate back to the v2-docs is not viable. It should be possible to do this using [Honkit theming](https://honkit.netlify.app/themes/), but this is not well documented and doesn't appear to work in practice - potentially a bug. It could possibly be done using some custom Javascript but that has other problems. Effort would be better spent on migrating the documentation.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/gaffer-doc/pull/294
