### ISSUE TITLE
Make v1docs javadocs display the correct version

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#290]
Currently the javadocs for Gaffer, gaffer-tools and koryphe are pulled from each respective repo's `gh-pages` branch, but this means that even though Gaffer 1.22.0 uses koryphe 1.14.0, the javadocs are shown for koryphe 2.1.0.

A short term fix would be to hard code and pull down the koryphe 1.14.0 javadoc, but this wouldn't work with Gaffer when Gaffer 2 is released fully and the javadocs show version 2.X.

Building the correct javadocs would take too long. Perhaps all 3 versions can be hardcoded and looked after manually, and the Gaffer one automatically with [update-v1docs-gaffer-version.yml](https://github.com/gchq/gaffer-doc/blob/bf6fa2a678f17fe6efae03dc347751841833954b/.github/workflows/update-v1docs-gaffer-version.yml)?

**Comment by GCHQDeveloper314** [comment]
I created a PR for this but it didn't seem to work with the Linux runner (details in the PR).

**Comment by GCHQDeveloper314** [comment]
The problem with the Linux runner has been bypassed by using `sed` instead of bash regex in the script.

**Comment by t92549** [comment]
Fixed by https://github.com/gchq/gaffer-doc/pull/291
