### ISSUE TITLE
Ways of working - two versions of the truth

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-doc#296]
@GCHQDeveloper314   The draft v2 doc WoW page says: "We have adopted the GitFlow Branching Model in order to support both Gaffer v1 and v2".

However the v1 WoW page is different. 

Redirect v1 page to point to the v2 page?

This principle may apply to other doc pages.

**Comment by GCHQDeveloper314** [comment]
Yes it would make sense to remove the content from that page and link to the new page instead. Same goes for any other information which is part of the v1 docs but not specific to Gaffer v1.

**Comment by t92549** [comment]
This isn't conflicting because the old page also links to the GitFlow Branching Model, it just does not name it. However, I agree with @GCHQDeveloper314 that all duplicated content should just point to the new page.

**Comment by GCHQDeveloper314** [comment]
Closed by #310
