### ISSUE TITLE
Add Python coding standards to doc

### ISSUE THREAD

**Issue by lb324567** [gchq/gaffer-doc#313]
As part of [gaffer-tools 137](https://github.com/gchq/gaffer-tools/issues/137) Python coding standards must be met for code to pass in the CI. 
gaffer-doc needs to be updated with information on these coding styles so that everyone developing for the repos knows the standards that we are not enforcing in the codebase. Documentation has been started, so just needs to be moved over.

**Comment by muskaan04** [comment]
i would like to contribute please explain what to do?

**Comment by GCHQDeveloper314** [comment]
Hello @muskaan04, unfortunately this isn't something we need any help with. My colleague created this to track some work they had already started, but used the wrong tag by mistake.
