### ISSUE TITLE
Document Gaffer 2.0 Federation changes

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-doc#317]
Gaffer 2.0 contains significant improvements to how federation works. Some of these require migration.

- [ ] Create a page explaining the breaking changes to federation in Gaffer 2.0 and how to migrate/mitigate these changes.
- [ ] Update existing federation documentation (e.g. Operations) to reflect the situation in Gaffer 2.0. _Note this cannot be done until this info has been migrated into the new docs._

**Comment by n3101** [comment]
The v1 doc says FederatedStore  is experimental. Not in v2.0!

I believe that theoretically it is possible to federate between a Mapstore and Accumulostore. However, I don't think those two are entirely compatible, so the v2.0 doc should set out what if anything is supported here.

**Comment by n3101** [comment]
The v1 doc has two sections:

Limit Access with Authentication
Disallow Public Access

I think it might read better if Disallow Public Access preceded the other one???

**Comment by n3101** [comment]
"Secure Access

Within the AddGraph operation, do not assign the "isPublic" parameter or assign it to false, this ensures the settings described in this section are not ignored."

What does this mean in practice? The earlier sections say that by default isPublic IS set to false. How does that square with this bit?

**Comment by n3101** [comment]
@GCHQDeveloper314 btw the v1 doc seems to have stopped executing the examples - it just takes you to the code. Is this deliberate?

**Comment by n3101** [comment]
"Proxy Store

The ProxyStore implementation is simply a Gaffer store which delegates all operations to a Gaffer REST API."

The Proxy Store doc does not mention federation at all, which implies it is something separate rather than a component used by federation.

**Comment by t92549** [comment]
@n3101 The proxy store is technically a separate component that could be useful without a federated store, but it should definitely be better described that proxy stores are very useful when paired with federated stores.

As part of the breaking changes descriptions, we should very clearly describe which operation chains will break, which will not break, and how to upgrade. See https://github.com/gchq/Gaffer/issues/2773
