### ISSUE TITLE
Add documentation for federated store visibility

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#319]
Add some documentation that describes how schemas are merged, specifically when visibility properties are shared, and when this can go wrong (with shared group names and different visibility property names).

See https://github.com/gchq/Gaffer/issues/1834

**Comment by GCHQDeveloper314** [comment]
Might be good to add some details on Store Traits and how these are merged as well.

**Comment by GCHQDeveloper314** [comment]
This should build on the Federated Store Guide updates done under #192. Ideally it would be started only once that issue is complete.

**Comment by t92549** [comment]
Blocked by https://github.com/gchq/Gaffer/issues/3045. We should not document how FederatedStore schema merging works until it is properly defined and tested.
