### ISSUE TITLE
Document Iterable and Iterator class migration/changes

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-doc#349]
In Gaffer 2.0.0, various classes were removed from [the `uk.gov.gchq.gaffer.commonutil.iterable`](http://gchq.github.io/Gaffer/uk/gov/gchq/gaffer/commonutil/iterable/package-summary.html) Gaffer package and migrated to [the `uk.gov.gchq.koryphe.iterable`](https://gchq.github.io/koryphe/uk/gov/gchq/koryphe/iterable/package-summary.html) Koryphe package.

In addition, the `Closeable` variants of all Iterable and Iterator classes were removed entirely.

These changes should be documented in the Gaffer 2 changelist and/or deprecations page.

**Comment by t92549** [comment]
It is [briefly mentioned](https://github.com/gchq/gaffer-doc/blob/v2docs/docs/gaffer2.0/changelist.md#removal-of-closeableiterable) in the changelist docs, but we should really mention all of the effected classes not just one of them
