### ISSUE TITLE
Update operations reference page

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#355]
Multiple operations have either been added or deleted and the [reference page](https://github.com/gchq/gaffer-doc/blob/v2docs/docs/reference/operations-guide/operations.md) not updated

**Comment by GCHQDeveloper314** [comment]
To clarify, the reference page should be checked to ensure the list of all operations it contains is up to date and complete. It shouldn't contain anything which has been removed in the latest Gaffer version and shouldn't be missing any operations.

To get a complete list of operations, use a fetch operations REST endpoint on the `accumulo-rest` REST. Note that the Spring REST doesn't have all possible operations on the classpath by default and so won't return everything.

I think the list should already be up to date from when I updated the page, if so this issue can be closed as "not planned".
