### ISSUE TITLE
Better describe FederatedOperation merge functions

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#357]
We should improve the [federation changes page](https://github.com/gchq/gaffer-doc/blob/v2docs/docs/gaffer2.0/federation-changes.md#new-merge-function-examples) to describe why users might want to change the merge function using the new FederatedOperation. Ideally including examples, pictures and diagrams of different merge functions and how they effect results.

**Comment by GCHQDeveloper314** [comment]
I think most of this information should be on a different or new page and not added to that changes page.

The use case of the changes is to describe difference between Gaffer 1 and 2, not to document standard behaviour which would be general use.
