### ISSUE TITLE
Clean Up Documentation

### ISSUE THREAD

**Issue by l46978** [gchq/gaffer-doc#427]
Tidying up parts of the documentation, ensuring links work correctly, more re-arrangements and adding fixes etc.

**Comment by t92549** [comment]
The accumulo operations page has the wrong heading: https://github.com/gchq/gaffer-doc/blob/cdfeb99614f5c8451e700ce2b08696e05f18a830/docs/reference/operations-guide/accumulo.md#L1

**Comment by GCHQDeveloper314** [comment]
Some ideas:

- Kerberos config page can probably be relocated to the admin guide as it's not specific to Gaffer 2.0 migration.
- There is duplication between [this page](https://github.com/gchq/gaffer-doc/blob/v2docs/docs/development-guide/example-deployment/project-setup.md#project-setup) and [this (more recent) page](https://github.com/gchq/gaffer-doc/blob/v2docs/docs/administration-guide/gaffer-config/config.md). This should be fixed, possibility by trimming down the later page.
- Make sure there are no uses of `ClosableIterable` in any of the examples.

**Comment by tb06904** [comment]
Couple of suggestions:
* Make sure any code snippets are following coding standards e.g. PEP 8 for python, google style for Java etc.
* The configuring gaffer section might need tweaking to remove references to a non existent example.
