### ISSUE TITLE
Add documentation for the addElementsFromHdfs logic updates

### ISSUE THREAD

**Issue by m55624** [gchq/gaffer-doc#51]
Setting numReduceTasks has now been deprecated, and instead setting the min and/or max should be used.  This means Accumulo, in most cases, will be able to choose the right amount of reducers for the user, based on the number of tablet servers.  If the minimum is more than the amount Accumulo chooses it will update to be more, and equally if the maximum is less than the Accumulo amount, it will reduce the number of reducers to be the maximum.

**Comment by p013570** [comment]
Merged into master.
