### ISSUE TITLE
Documentation for Extraction Functions and Operations

### ISSUE THREAD

**Issue by m607123** [gchq/gaffer-doc#76]
Documentation should be written for the recent additions of a number of Extraction functions in Koryphe, and operations in Gaffer.
See:
gchq/koryphe#60
gchq/koryphe#74

gchq/Gaffer#1573
gchq/Gaffer#1612

**Comment by m607123** [comment]
Issue completed, waiting for features to be merged.

**Comment by p013570** [comment]
Merged into master.
