### ISSUE TITLE
Documentation for new Operations, Functions and Predicates

### ISSUE THREAD

**Issue by m607123** [gchq/gaffer-doc#83]
Documentation and examples to be added for the:
`If` : gchq/koryphe#81
`IsLongerThan` : gchq/koryphe#89
`Length` : gchq/koryphe#85

`ExtractId` and `ExtractProperty` : gchq/Gaffer#1705
`If` : gchq/Gaffer#1649

**Comment by p013570** [comment]
Merged into master.
