### ISSUE TITLE
Update sketches documentation with link to performance comparison of HLLs

### ISSUE THREAD

**Issue by gaffer01** [gchq/gaffer-doc#93]
We should update the documentation on sketches to include this link to show the difference in performance of Clearspring's HLL and Datasketches HLL (https://datasketches.apache.org/docs/HLL/Hll_vs_CS_Hllpp.html) and use this to justify recommending use of datasketches over Clearspring.

**Comment by p013570** [comment]
We should also update the Cardinalities walkthrough to use the Datasketches HLL instead.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/gaffer-doc/pull/351
